### ISSUE TITLE
Better location for initial FOB

### ISSUE THREAD

**Issue by R1ZLaUK** [martinco/Co-ops#10]
Look at the possibility of a better location for our first base.

**Comment by martinco** [comment]
Molos airfield was the discussed initial location for invasion

**Comment by R1ZLaUK** [comment]
I've been working on this, i will test what i have a bit more and maybe upload to the server for play testing.

**Comment by R1ZLaUK** [comment]
Moved base to Molos, debugged and now play testing on server.
